### ISSUE TITLE
Suggest!!!

### ISSUE THREAD

**Issue by Longalei** [driver733/kotlin-vs-java#21]
Your project is very excellent. Especially the webpage with java and kotlin.But I find something is wrong with the code. As a newer,may be it's misleading.

For example:
![wrong](https://user-images.githubusercontent.com/13430267/71051730-32ce4500-2184-11ea-908b-7911923c5374.png)

Surely，You can do better for more honor.

**Comment by driver733** [comment]
Hello. Can you explain what exactly is wrong with code?

**Comment by Longalei** [comment]
> Can you explain what exactly is wrong with code?

the variable `name` should be initialized when you defined `final`.

**Comment by driver733** [comment]
In Java, final fields can be initialized through a constructor. Try to compile this code snippet locally and you'll see no errors.

**Comment by Longalei** [comment]
> In Java, final fields can be initialized through a constructor. Try to compile this code snippet locally and you'll see no errors.

We should initialize a final variable in Java, otherwise, a compiler can throw a compile-time error.
