### ISSUE TITLE
Java Version & kotlin Version

### ISSUE THREAD

**Issue by disappearwang** [driver733/kotlin-vs-java#22]
Hi,
You've done a cool project!

Could you specify the version of two language. Maybe the codes should be re-organized by version in the future in order to avoid becoming obsolete.

For example, le chapter : **Strings II**
is true for java version < 13 but this feature (""" {formed String}""") is added in JAVA 13.

Regards

**Comment by driver733** [comment]
Thanks for the feedback!

I totally agree with you. I, [and many others](https://news.ycombinator.com/item?id=21807233), believe that the latest stable versions (without experimental features) of the languages should be compared. As of now, it's `Java 13` and `Kotlin 1.3.60`. The versions can be specified in the footer.

```
Kotlin - v. 1.3.60
Java - v. 13
```
