### ISSUE TITLE
Playing favorites?

### ISSUE THREAD

**Issue by AnyTimeTraveler** [driver733/kotlin-vs-java#24]
At least to me, this site seems to be playing favorites to Kotlin over Java without declaring that anywhere (that I've found).

What I find off about this:
 - The site is titled "Kotlin vs. Java", even though alphabetically J comes before K, suggesting a focus on Kotlin.
 - The Java code in the Concurrency examples has obvious syntax errors.
 - The Optional feature of Java is completely ignored in the nullability examples.
 - Sometimes Lombock is used, sometimes it isn't, which either shows a lack of interest in consistency or in Java.
 - The site doesn't show any scenarios where Kotlin is worse.
 - The site also ignores the issues with calling Kotlin code from Java. And while the other way works much better, last I heard that there were still issues, especially when throwing annotation processing into the mix.

On the counterside, some examples do show Java in a better light, like Kotlin's removal of the tenary operator in favor of writing a full if else statement in one line.

**Comment by driver733** [comment]
Thanks for the feedback. If you believe that some examples are flawed or missing, please go ahead and submit a PR. Also, if you want to have any issues to be fixes, be sure to describe them in detail. For instance,

> The Java code in the Collections examples has obvious syntax errors. 

is not specific enough.
